### ISSUE TITLE
weather command not working

### ISSUE THREAD

**Issue by randyknighton** [innogames/slack-bot#125]
## weather command not enabled by default

when running the bot after initial install the weather command isn't listed as a command (yes I got an API key and uncommented the lines in config.yaml)

## Expected behavior

when running "help" command it should list "weather" as a valid command

I get the following:   Invalid command: weather

**Comment by brainexe** [comment]
The [documentation is](https://github.com/innogames/slack-bot#weather-command) maybe missing one point:
The openweathermap-API requires an API-Token. If there is no token defined in the config.yaml, the command is not loaded and therefore not available. The same behavior is place fir gitlab/github/jenkins etc

See the config structure of the readme file: 
```
open_weather:
  apikey: "612325WD623562376678"
  location: "Hamburg, DE"
  units: "metric"
``` 

-> just register [here on openweathermap](https://openweathermap.org/api) and generate a free API key (as there are just a few reqs, the free plan is totally enough)

**Comment by randyknighton** [comment]
I got an API token and put it in the config.yaml file .. I guess that wasn't clear in my comment above.

**Comment by brainexe** [comment]
okay, sorry I missed this part.
That's strange, but I think I found one issue: there was a typo in the "open_weather" part of the config.example.yaml:
-> "api_key" should be "apikey".

Sadly the current yaml/mapstructure/iper parser is not strict anymore and is not complainig anymore...maybe I'll add some kind of validation again.

**If it's still broken:**
I also pushed a new command/flag  to master to be able to dump the config (after loading the yaml file(s), merging with the default config etc.)
Could you then please update and run  `go run cmd/bot/main.go -show-config`  and check the part of "OpenWeather".

It should look similar like this: 
```
...
   "OpenWeather": {
      "Apikey": "01XXXX84b7XXXXXX",
      "Location": "Hamburg",
      "Units": "metric"
   },
```


Do you have the OpenWeather? is a "Apikey" defined?

**Comment by randyknighton** [comment]
I updated and changed the "api_key" to be "apikey"

this is what the output had on the `go run cmd/bot/main.go -show-config`

**Comment by randyknighton** [comment]
I get the weather command now to display data.
