### ISSUE TITLE
State storage: Redis backend

### ISSUE THREAD

**Issue by adampetrovic** [innogames/slack-bot#14]
My team has started using this as the base for our slack bot and I must say the project has been a pleasure to work with. Thank you!

I have a few ideas / feature requests that we'd benefit from (and hopefully others too!) in practice. I'll try to make an effort in the coming weeks to send up a PR for each.

For this issue though,

Currently the project only supports storing JSON state in a local file. For those that have deployment models that require 12 factor properties this isn't ideal.

What would this require?

I think we should convert https://github.com/innogames/slack-bot/blob/master/bot/storage/store.go into a generic storage interface, then have a Scribble implementation as well as a Redis implementation. Depending on the configuration, we can choose one at runtime.

Let me know what you think.

**Comment by brainexe** [comment]
Hey @adampetrovic , 
improving the "storage" module is on the top of my ToDo list already as it's one of the oldest/shittiest parts of the projects. And there is also the plan to provide a Redis implementation. Give me a few days and I'll try to extract it to be much more flexible in terms of storing such data.

**Comment by brainexe** [comment]
@adampetrovic please check #16. This add a more generic "storage" and basic support for a redis storage. Use the redis storage by using this snippet:
```
SetStorage(NewRedisStorage(redisClient))
```

**Comment by brainexe** [comment]
merged into master
