### ISSUE TITLE
Support interactions with cloud vendors like AWS

### ISSUE THREAD

**Issue by joosangkim** [innogames/slack-bot#248]
**Is your feature request related to a problem? Please describe.**
I want to implement simple interaction with AWS resource(CF) so I create a PR about interfaction with AWS CF (https://github.com/innogames/slack-bot/pull/246) 

**Describe the solution you'd like**
What do you think about create multiple cloud vendors' sdk and make it plugable.

**Describe alternatives you've considered**

**Additional context**

**Comment by brainexe** [comment]
Hey @joosangkim thx for your contribution 🥳 
It just sometimes takes some days until I can check all new PRs :) 

I just [left a comment here](https://github.com/innogames/slack-bot/pull/246#issuecomment-979732636) whats left to get your PR merged

**Comment by brainexe** [comment]
PR got merged, thx again :)
