### ISSUE TITLE
load credentials from env var

### ISSUE THREAD

**Issue by rkirimov** [innogames/slack-bot#416]
**Is your feature request related to a problem? Please describe.**
It would be great to provide an option to load credentials from environment variables in addition to `config.yaml` option.

**Describe the solution you'd like**
Adding functionality to `loader.go` to load environment variables and to replace any that match variables in config.yaml file. Or any other solution that allows me to configure credentials as env var instead of hard-coding them into the config file.

**Comment by brainexe** [comment]
Here is an explanation: https://github.com/innogames/slack-bot/issues/15#issuecomment-1531888591
If there are issues with it, please ping me. There might be some cases not working, like lists of nested structure, like "crons" or "commands", but base config is working with it :)
